version: '3.9'
services:
  db:
    image: postgres:15
    container_name: test_case_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: test_case_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: testdb
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]

volumes:
  db_data:
